Product.create(name: "Bread", price: 500, category: "Food", image: "images/products/bread.jpg")
Product.create(name: "Shoes", price: 4500, category: "Fashion", image: "images/products/shoes.jpg")
Product.create(name: "Rice", price: 4000, category: "Food", image: "images/products/rice.jpg")
Product.create(name: "Water", price: 100, category: "Drink", image: "images/products/water.jpg")
Product.create(name: "Apple", price: 300, category: "Fruit", image: "images/products/apple.jpg")
Product.create(name: "Dried Pepper", price: 1200, category: "Pepper", image: "images/products/dried-pepper.jpg")
Product.create(name: "Fresh Pepper", price: 800, category: "Pepper", image: "images/products/fresh-pepper.jpg")
Product.create(name: "Honey Beans", price: 2000, category: "Food", image: "images/products/hornybeans.jpg")
Product.create(name: "Maggi Star", price: 600, category: "Season", image: "images/products/maggi.jpg")
Product.create(name: "Macaroni", price: 1500, category: "Food", image: "images/products/macaroni.jpg")
Product.create(name: "Milk (Family Pack)", price: 2500, category: "Food", image: "images/products/milk.jpg")
Product.create(name: "Palm Oil", price: 3000, category: "Season", image: "images/products/palm-oil.jpg")
Product.create(name: "Vegetable Oil", price: 3500, category: "Season", image: "images/products/vegetable-oil.jpg")
Product.create(name: "Vegetable", price: 500, category: "Fruit", image: "images/products/vegetable.jpg")
Product.create(name: "Yam", price: 2800, category: "Food", image: "images/products/yam.jpg")
Product.create(name: "Wooden Utensils", price: 5000, category: "Utensils", image: "images/products/wooden.jpg")
Product.create(name: "Spaghetti (Large Pack)", price: 2000, category: "Food", image: "images/products/spaghetti-1.jpg")
Product.create(name: "Spaghetti (Small Pack)", price: 1000, category: "Food", image: "images/products/spaghetti-2.jpg")
